<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  
  <ItemGroup>
    <Reference Include="Intalio.Case.Core">
      <HintPath>Pak\dllsV7.1.0\Intalio.Case.Core.dll</HintPath>
    </Reference>
    <Reference Include="Intalio.Case.Portal">
      <HintPath>Pak\dllsV7.1.0\Intalio.Case.Portal.dll</HintPath>
    </Reference>
    <Reference Include="Intalio.Case.Portal.Core">
      <HintPath>Pak\dllsV7.1.0\Intalio.Case.Portal.Core.dll</HintPath>
    </Reference>
    <Reference Include="Intalio.Core">
      <HintPath>Pak\dllsV7.1.0\Intalio.Core.dll</HintPath>
    </Reference>
    <Reference Include="Intalio.Core.UI">
      <HintPath>Pak\dllsV7.1.0\Intalio.Core.UI.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>Pak\dllsV7.1.0\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>Pak\dllsV7.1.0\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <HintPath>Pak\dllsV7.1.0\Microsoft.EntityFrameworkCore.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyModel">
      <HintPath>Pak\dllsV7.1.0\Microsoft.Extensions.DependencyModel.dll</HintPath>
    </Reference>
  </ItemGroup>


 

</Project>
